// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEqXpSgJ-U-TfWV9JR5EacFd9Uduapa2Y',
    appId: '1:73562282065:web:d8fae5beb89281b8828070',
    messagingSenderId: '73562282065',
    projectId: 'neoparentalapp',
    authDomain: 'neoparentalapp.firebaseapp.com',
    databaseURL: 'https://neoparentalapp-default-rtdb.firebaseio.com',
    storageBucket: 'neoparentalapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsYUAQVVCPIT6fgEM0Whyh0vDn7o4oo1E',
    appId: '1:73562282065:android:39d36f38f43e5106828070',
    messagingSenderId: '73562282065',
    projectId: 'neoparentalapp',
    databaseURL: 'https://neoparentalapp-default-rtdb.firebaseio.com',
    storageBucket: 'neoparentalapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDEeY7eskYfu1XCgHE5gen39MR4IHRzVo',
    appId: '1:73562282065:ios:17e9091d9512da61828070',
    messagingSenderId: '73562282065',
    projectId: 'neoparentalapp',
    databaseURL: 'https://neoparentalapp-default-rtdb.firebaseio.com',
    storageBucket: 'neoparentalapp.firebasestorage.app',
    iosBundleId: 'com.example.parent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDEeY7eskYfu1XCgHE5gen39MR4IHRzVo',
    appId: '1:73562282065:ios:17e9091d9512da61828070',
    messagingSenderId: '73562282065',
    projectId: 'neoparentalapp',
    databaseURL: 'https://neoparentalapp-default-rtdb.firebaseio.com',
    storageBucket: 'neoparentalapp.firebasestorage.app',
    iosBundleId: 'com.example.parent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEqXpSgJ-U-TfWV9JR5EacFd9Uduapa2Y',
    appId: '1:73562282065:web:5e531b9f97b771d0828070',
    messagingSenderId: '73562282065',
    projectId: 'neoparentalapp',
    authDomain: 'neoparentalapp.firebaseapp.com',
    databaseURL: 'https://neoparentalapp-default-rtdb.firebaseio.com',
    storageBucket: 'neoparentalapp.firebasestorage.app',
  );
}
